name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [master]
  # 手动触发部署
  # workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: |
          npm install
          npm run docs:build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "jonylee.cn@gmail.com"
          git config --global user.name "GitHub Actions"
          cd docs/.vuepress/dist
          git init
          git remote add deploy "https://${{ secrets.GITHUB_TOKEN }}@github.com/jony-lee/jonylee.github.io.git"
          git add .
          git commit -m "Deploy website"
          git push --set-upstream deploy master --force
