name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [master]
  # 手动触发部署
  # workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: |
          npm install
          npm run build
          mv docs/.vuepress/public/ads.txt docs/.vuepress/dist/
          echo "jonylee.cn" > docs/.vuepress/dist/CNAME

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Publish
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs/.vuepress/dist'
          destination-github-username: 'jony-lee'
          destination-repository-name: 'jony-lee.github.io'
          user-email: jonylee.cn@google.com
